### ISSUE TITLE
4.2 installing issues

### ISSUE THREAD

**Issue by Sim1603** [blackears/parrotLipsync#10]
Im trying to get parrot to work in 4.2 but fail. In 4.1 i had to install the libraries again which worked, but for 4.2 blender keeps coming up with the error that whisper timestamped is not found. 

My python coding is like non existent so im struggling to get it to work. Or is this a 4.2 issue?
![image](https://github.com/user-attachments/assets/6761e6a6-6300-4f23-89fa-fccdfd3c6a8d)
![image](https://github.com/user-attachments/assets/ca7310f1-e9cc-4bc1-a7fb-eda7b495b020)

Sorry for the fuss!

**Comment by blackears** [comment]
Blender updated  how installing modules work in 4.2  I'm not sure why this is not working.   In some of my test runs it works, and in others I'm getting the same error you are.  I've posted a question and hope to fix this soon.

https://blenderartists.org/t/how-to-install-python-module-in-blender-4-2/1545426

**Comment by blackears** [comment]
It looks like this is likely due to a permissions error.  You can change permissions on your site-packages directory to get around this, but I don't think this is recommended by Blender.  I'm looking into other strategies for installing modules in 4.2.

https://projects.blender.org/blender/blender/issues/126751

**Comment by Sim1603** [comment]
Thanks for the trouble. Im using 4.1 currently if i want to use parrot. 

But in the long run might be nice to be able to use it with 4.2 as well. Anyways love the addon, saved me so much time.

**Comment by KhanArts** [comment]
![Screenshot 2024-09-13 135332](https://github.com/user-attachments/assets/9a110095-4dd4-47c0-8512-a435a007cfb1)
![Screenshot 2024-09-13 135332](https://github.com/user-attachments/assets/cfc47940-2753-4934-af8c-d86d0eb68707)
it gives me this error whisper time not installed blender 4.2

**Comment by blackears** [comment]
Parrot 1.1.0 should resolve this issue.  Please let me know if you're still having issues.

**Comment by blackears** [comment]
Glad it's working now.
