### ISSUE TITLE
"TypeError: argument of type 'NoneType' is not iterable" when trying to render lip sync

### ISSUE THREAD

**Issue by etherealxx** [blackears/parrotLipsync#13]
I got this error when trying to render lip sync to action.
```
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\whisper_timestamped\__init__.py", line 1, in <module>
    from whisper import available_models, _download, _MODELS # defined in __init__.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\stable\blender-4.1.1-stable.e1743a0317bc\4.1\python\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
actually before this error, another error happens, saying that module `whisper` is not installed, even though i installed both gruut and `whisper_timestamped`. so i manually installed `whisper` to the blender python. then i have this error.

Keep in mind i'm still using Blender 4.1.1, Windows 11

this is my `where python`
```
C:\Program Files\Blender Foundation\stable\blender-4.1.1-stable.e1743a0317bc\4.1\python\bin>where python
C:\Program Files\Blender Foundation\stable\blender-4.1.1-stable.e1743a0317bc\4.1\python\bin\python.exe
C:\Users\Ethereal\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\Ethereal\AppData\Local\Microsoft\WindowsApps\python.exe
```
do i need to install it with administrator privilege or something?

**Comment by etherealxx** [comment]
> Blender completely changed how 3rd party Python modules are handled in version 4.2 and I'm still trying to figure out a fix. For now, the addon will still work with Blender 4.1.

thanks for answering, but as i said before, i still use Blender 4.1.1 . Does that mean i nead to downgrade 4.1.0? Or you maybe misread my issue?🙏

**Comment by blackears** [comment]
Sorry, I was only aware of this issue with Blender 4.2.  I'm not sure why there is an issue with Blender 4.1.1.  It is possible that 4.1.1 had the same system that 4.2 does.  I have tested it on 4.1.0.  Would you be able to try it on an older version of Blender and see if you're still having the same problem?

**Comment by blackears** [comment]
Parrot 1.1.0 should resolve this issue.  Please let me know if you're still having issues.

**Comment by blackears** [comment]
Closing in favor of https://github.com/blackears/parrotLipsync/issues/10

**Comment by etherealxx** [comment]
Let me clarify a bit. so i tried on blender 4.0.2, first time it also have an error, but after i reinstalled torch, it works as expected. I haven't told this before, but midway installing the extension on 4.1, i hit the OS error because of no space left on C: system drive, so i removed some stuff and continued the intallation. Turns out that will mess with the installation.
So probably this problem was from my side, or from the lack of error-checking when some dependencies aren't installed correctly.
Now let me ask, your new 1.1.0, does it still support 4.1/4.0? since from my limited knowledge, 4.2 extension has different folder layout compared to 4.1 and below. Last time i checked, updating an addon, it breaks since it cannot be installed.

**Comment by blackears** [comment]
You can't use 1.1.0 on 4.1 since it is packaged using Blender's new extension convention which 4.1 can't handle.  But this just has to do with how it is being packaged.  If you took the python script itself and packaged it the old addons way, it ought to work on 4.1.

My dev environment is Windows, so I can't give much advice on Mac specific install issues.

**Comment by etherealxx** [comment]
> Keep in mind i'm still using Blender 4.1.1, Windows 11
> 
> this is my `where python`
> 
> ```
> C:\Program Files\Blender Foundation\stable\blender-4.1.1-stable.e1743a0317bc\4.1\python\bin>where python
> C:\Program Files\Blender Foundation\stable\blender-4.1.1-stable.e1743a0317bc\4.1\python\bin\python.exe
> C:\Users\Ethereal\AppData\Local\Programs\Python\Python310\python.exe
> C:\Users\Ethereal\AppData\Local\Microsoft\WindowsApps\python.exe
> ```
> 
> do i need to install it with administrator privilege or something?

nah i already said i'm using win 11. Maybe i just need to make sure my system space is free next time. Maybe having at least 2GB free space on system directory is a requirement or something during installation.

**Comment by blackears** [comment]
Sorry, I'm not sure why it might not be installing properly.  A lack of free space could definitely be a reason.  I don't really know a lot about how python manages it's modules and as long as you're using pip to install them on the python that ships with Blender, that ought to work.  You could also try using a smaller language model in case that is what is causing the issue.

Sorry about the Mac - I was getting this confused with another issue.
