### ISSUE TITLE
for the new update 1.1

### ISSUE THREAD

**Issue by KhanArts** [blackears/parrotLipsync#15]
it keepsshowing me this when i hit render lypsynch or did i do something wrong while installing
![Screenshot 2024-09-22 093105](https://github.com/user-attachments/assets/48e2ea21-5fb6-47f7-b3f4-6fc3722886a0)

**Comment by KhanArts** [comment]
![Screenshot 2024-09-22 093105](https://github.com/user-attachments/assets/8edfad64-7050-44d8-b00d-322ebdebafcd)
![Screenshot 2024-09-22 093105](https://github.com/user-attachments/assets/59d098b4-469c-455f-851d-852f06387a81)

**Comment by blackears** [comment]
Those errors are all related to internet connections.  The program needs to download some dictionaries, at least the first time it runs (I think it can reuse them after that) so it needs internet access.  Are you connected to the internet?

**Comment by KhanArts** [comment]
![Screenshot 2024-09-23 103920](https://github.com/user-attachments/assets/eb44be99-1768-4ae5-94de-6aeeae753f41)
it worked now i wasnt on internet that time i forgot tnx

**Comment by KhanArts** [comment]
the only thing is that it quickly finish without reaching the end of the audio of lip-synch i will try another fresh work just incase it did that again

**Comment by blackears** [comment]
Glad it's working now.
