### ISSUE TITLE
'Modules Installed () from ...' but doesn't appear in the Add-ons list

### ISSUE THREAD

**Issue by edgecate** [blackears/parrotLipsync#17]
![image](https://github.com/user-attachments/assets/130b34f9-85a3-4d71-8325-e9590a1ab49a)

I couldn't get Parrot Lipsync installed on Blender 4.2, so I tried 4.1, but ran into this issue where I install the add-on, and the following message appears suggesting a successful installation: 
Modules Installed () from 'C:\\Users\\NAME\\Downloads\\parrotLipsync-master.zip' into 'C:\\Users\\NAME\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons'

But Parrot Lipsync doesn't appear in the list of Add-ons:
![image](https://github.com/user-attachments/assets/1ac99feb-ac61-486a-b24a-ffad52555e3b)

I also downloaded all the zip files from the branches & tags, and the same result happens for all zip files.

**Comment by edgecate** [comment]
Fixed it. The problem was me - I downloaded your source zip, but not the Released versions.
I downloaded parrotLipsync_1.0.5.zip from here: https://github.com/blackears/parrotLipsync/releases/
And installation was successful.
![image](https://github.com/user-attachments/assets/2c6b5e74-f0e7-41f5-a767-4fc75d66ce5a)

**Comment by blackears** [comment]
Version 1.0.5 works on Blender 4.1, version 1.1.0 is for Blender 4.2 and higher.  The Blender team made big changes to how plugins are handled, so you can't use 1.0.5 on Blender 4.2.
