### ISSUE TITLE
In the absence of a discussion tab or alternative point of contact

### ISSUE THREAD

**Issue by weThere** [blackears/parrotLipsync#18]
Half-way excuse to ask why it seemingly is not possible to give on ko-fi firstly as I'm aiming give slightly above blendermarket-asking due to assumed future time savings, patreon does not allow one-offs seemingly.

Secondly more so idea entertainment than feature request as I'm ignorant to how much or little effort would ensue programmatically:

- Storing parrot settings on an armature-to-armature basis in multi-char scenes. Adds some dynamics in the case of recording voice and animating simultaneously where dialog is intended to overlap, abrupt each other etc.

- Probably blatantly obvious but is it by extension be possible to expand audio-action inference to include any action in general but here mainly facial/brow grimacing or gesturing (probably better off inferring sound to spatial transforms than actions)? Assumedly for different variables (tone of voice, animated value of how emotional/reactive the character is to their voice.)

(Conceptually inspired by what you'd see in an addon like this https://github.com/example-sk/audvis or external "nvidia omniverse": https://docs.omniverse.nvidia.com/extensions/latest/ext_audio2gesture.html as I assume waveform analysis is what whisper does on runtime in the roughest sense. I flee external pipelines like the plague unless they connect to blender realtime which nvidia apparently does not yet.)

Big cheers

**Comment by blackears** [comment]
Hi.  The two projects you linked to are quite different.  The first is just decomposing the audio into its waveform components and then visualizing them - there's no AI involved, just a Fourier transform.  The second is using AI to guess at appropriate gestures to go along with the dialog.

Parrot uses the allosaurus library to convert spoken audio in to phonemes.  It doesn't handle gestures, but if you know how to use Blender's NLA library, you can overlay the lip movements on facial expressions or other gestures to combine the two.  Ive' been thinking about adding a feature to analyze the audio to add facial expressions too, but I've been busy with other tasks so far.

**Comment by blackears** [comment]
I think using Blender's NLA is the best way to combine lip movements with other gestures.  It is what I had in mind when I was designing the extension.

I've added an option in the Sponsors button at the top of the page that will let you submit through Github directly.  Unfortunately, Github is not letting me post a link directly to my Stripe account.  However, if you'd like to make a one-time donation, Ko-fi can let you do that.

Thanks!  I'm still working on developing a video game, but there is always so much to do with that.

**Comment by weThere** [comment]
There you go; became kofi in the end, github has pulled the plug on paypal sponsors, and don't accept my card. If AI overlord ever becomes lacking in the character animation department for your projects I'll be one of your many options happily.

Take care in any case for now.
