### ISSUE TITLE
Cannot install parrotLipsync in Blender on Mac

### ISSUE THREAD

**Issue by daleasberry-n** [blackears/parrotLipsync#19]
Parrot Lipsync 1.1.0
Blender 4.2.3 (4.2.3 2024-10-15)
Mac M1 Pro with Sequioa 15.1

File->Edit->Preferences
Select "Get Extensions" Tab.
Drop down "Install from Disk..."
Select "parrot_lipsync-1.1.0-macos_x64.zip"

Doesn't show up as an available Extension

**Comment by blackears** [comment]
I've updated the mac release in https://github.com/blackears/parrotLipsync/releases/tag/v1.1.0.  Could you download it and try again?  The original upload did not include support for arm64 macs, and this may be causing the issue.  Please let me know if this works.

**Comment by daleasberry-n** [comment]
Thank you. Just downloaded. 

Still not showing in the list of available extensions.

**Comment by blackears** [comment]
Can you please post anything that is printed in the console window?

**Comment by daleasberry-n** [comment]
Package should have been installed but not found: parrot_lipsync

**Comment by blackears** [comment]
I'm afraid that doesn't tell me much.  Blender completely changed how modules are installed in 4.2, and I don't have a mac so I can't test this. 

If you open the console window by choosing the `Window/Toggle System Console` menu item.  Then just cut and paste what is printed in that window here.

**Comment by daleasberry-n** [comment]
Ugh. Looks like Blender is absolutely no help on this. I used --debug-all and here are the 15 lines before and after I tried to load parrot_lipsync:

loading preset: /Applications/Blender.app/Contents/Resources/4.2/scripts/presets/keyconfig/Blender.py
bl_app_template_utils.reset('')
Extension version cache: no extensions, skipping cache data.
	addon_utils.enable io_anim_bvh
	addon_utils.enable io_curve_svg
	addon_utils.enable io_mesh_uv_layout
	addon_utils.enable io_scene_fbx
	addon_utils.enable io_scene_gltf2
	addon_utils.enable cycles
	addon_utils.enable pose_library
	addon_utils.enable bl_pkg
INFO Checking repository "extensions.blender.org" for updates...
INFO Refreshing extensions list for "extensions.blender.org"...
INFO Extensions list for "extensions.blender.org" updated
Extension version cache: up to date.
Package should have been installed but not found: parrot_lipsync
	addon_utils.disable io_anim_bvh
	addon_utils.disable io_curve_svg
	addon_utils.disable io_mesh_uv_layout
	addon_utils.disable io_scene_fbx
	addon_utils.disable io_scene_gltf2
	addon_utils.disable cycles
	addon_utils.disable pose_library
	addon_utils.disable bl_pkg
Saved session recovery to "/var/folders/hx/zb1zj4j57ns_2wwbzftkyvbc0000gn/T/quit.blend"

Blender quit

**Comment by blackears** [comment]
I'm not sure what's going wrong.  I don't think those messages are related to the extension.  My best guess is that I've missed a library to bundle, but I can't diagnose that.

You could still use Parrot 1.0.5 on Blender 4.1, if that works for you.
