### ISSUE TITLE
How to use headless?

### ISSUE THREAD

**Issue by sebastianrueckerai** [blackears/parrotLipsync#2]
Hi!

You made an awesome tool here, just bought it! :)

One question: I would like to use this in headless mode, to do remote rendering. I set up my blender file and then just switch the sound track depending on what I want to render. How do I trigger "Render Lipsync to action" from a script so I can do it via the command line without using the GUI?

Cheers!

-------
Edit:

It is possible to execute python scripts from the command line, so I could extract and run `render_lipsync_to_action(context, tgt_action, seq):`, but I am unsure what inputs it needs and if I need to do something so it has the right context.

**Comment by blackears** [comment]
I've added an example that shows how to run in headless mode for NLA generation.  `render_lipsync_to_action` should be pretty similar.

**Comment by sebastianrueckerai** [comment]
Ah, nice! :)
https://github.com/blackears/parrotLipsync/blob/master/examples/headless_example/run_headless.py

**Comment by sebastianrueckerai** [comment]
Hey @blackears this is off-topic! Let me know if there is a better channel like discord to discuss this.

Parrot lipsync works nicely, but timing of the poses is not perfect and sometimes exaggerated. I suppose this is  because we only get word level timestamps and those assume no pause between words. 

I think this could be improved quite simply by adding the option to use the volume of the speakers voice to interpolate between the currently chosen phoneme and the rest pose. 
Example: When the sound is over a certain threshold everything is like it is now. If the sound is under this threshold we start interpolating towards the rest pose (closed mouth). This way we can smooth out the mouth movement.

This is basically integrating this simple approach with what parrot is doing: https://www.youtube.com/watch?v=_q6w3lo98rs&t=2s

This will have problems if there is a lot of other noise in the recording but otherwise might improve things. I just started looking into this but I would be open to help on this though I am not sure whether I can do it on my own. I have done blender scripting before but never anything involving UI or a full fledged add on. Still, would be happy to help.

Thanks again for making this tool! ;)

**Comment by sebastianrueckerai** [comment]
Oh, and I fear this is not quite working yet!

I pulled the latest version and tried to run the python script for the headless example but it failed with 
`AttributeError: Calling operator "bpy.ops.parrot.render_lipsync_to_object_nla" error, could not be found`

Here is the full output:
```
PS C:\Users\Rueck\Dropbox\BlenderLipSyncTest\parrotLipsync\examples\headless_example> blender -b headless_demo.blend -P run_headless.py
Blender 4.1.0 (hash 40a5e739e270 built 2024-03-26 02:02:39)
Read prefs: "C:\Users\Rueck\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Read blend: "C:\Users\Rueck\Dropbox\BlenderLipSyncTest\parrotLipsync\examples\headless_example\headless_demo.blend"
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_legs"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_arms"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_arms"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_legs"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_arms"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_legs"].show_viewport[0]
++++++++++++Test parrot headless
Traceback (most recent call last):
  File "C:\Users\Rueck\Dropbox\BlendeAttributeError: Calling operator "bpy.ops.parrot.render_lipsync_to_object_nla" error, could not be found
rLipSyncTest\parrotLipsync\examples\headless_example\run_headless.py", line 12, in <module>
    bpy.ops.parrot.render_lipsync_to_object_nla()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.parrot.render_lipsync_to_object_nla" error, could not be found

Blender quit
PS C:\Users\Rueck\Dropbox\BlenderLipSyncTest\parrotLipsync\examples\headless_example>



```

**Comment by blackears** [comment]
Is Parrot installed?  That error looks like the Parrot init script didn't run.  And if that's the entire output, it doesn't look like there was an error loading Parrot.

**Comment by blackears** [comment]
Also, make sure that you've upgraded to version 1.0.1.  I made some changes to path names.

**Comment by sebastianrueckerai** [comment]
Hi!

I updated the Addon:
![image](https://github.com/blackears/parrotLipsync/assets/83586913/436735db-65b5-4c2a-b16a-64a0989645b7)

When I check in the blender console now:
```
>>> dir(bpy.ops.parrot)
['lipsync_to_action', 'reload_phoneme_table', 'render_lipsync_to_object_nla']
```

Unfortunately I get a different error now:

```
PS C:\Users\Rueck\Dropbox\BlenderLipSyncTest\parrotLipsync\examples\headless_example> blender -b headless_demo.blend -P run_headless.py
Blender 4.1.0 (hash 40a5e739e270 built 2024-03-26 02:02:39)
Read prefs: "C:\Users\Rueck\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Read blend: "C:\Users\Rueck\Dropbox\BlenderLipSyncTest\parrotLipsync\examples\headless_example\headless_demo.blend"
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_arms"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_legs"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_arms"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_legs"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_legs"].show_viewport[0]
WARN (bke.anim_sys): C:\Users\blender\git\blender-v410\blender.git\source\blender\blenkernel\intern\anim_sys.cc:4204 BKE_animsys_eval_driver: invalid driver - modifiers["mask_arms"].show_viewport[0]
++++++++++++Test parrot headless
Traceback (most recent call last):
  File "C:\Users\Rueck\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\parrotLipsync\parrot_lipsync.py", line 587, in execute
    if not importlib.util.find_spec(mod):
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
Error: Python: Traceback (most recent call last):
  File "C:\Users\Rueck\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\parrotLipsync\parrot_lipsync.py", line 587, in execute
    if not importlib.util.find_spec(mod):
           ^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'util'
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\Rueck\Dropbox\BlenderLipSyncTest\parrotLipsync\examples\headless_example\run_headless.py", line 12, in <module>
    bpy.ops.parrot.render_lipsync_to_object_nla()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Rueck\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\parrotLipsync\parrot_lipsync.py", line 587, in execute
    if not importlib.util.find_spec(mod):
           ^^^^^^^^^^^^^^
```

**Comment by blackears** [comment]
I'm not sure why you're getting hat.  Importlib should be standard Python module.  Have you installed whisper_timestamped and gruut?  Maybe try installing importlib as well?

**Comment by blackears** [comment]
Also make sure you've installed everything to the Blender python and not some other python installation.  Does Parrot work in you run it in Blender without headless mode?

**Comment by sebastianrueckerai** [comment]
So lipsync to action works fine if I do it in normal Blender (not headless).
Here are the installed packages of my Blenders Python:

```
PS C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\bin> .\python.exe -m pip freeze
autopep8==1.6.0
Babel==2.14.0
certifi==2021.10.8
charset-normalizer==2.0.10
colorama==0.4.6
Cython==0.29.30
dateparser==1.1.8
docopt==0.6.2
dtw-python==1.4.2
filelock==3.13.3
fsspec==2024.3.1
gruut==2.3.4
gruut-ipa==0.13.0
gruut_lang_en==2.0.0
idna==3.3
Jinja2==3.1.3
jsonlines==1.2.0
llvmlite==0.42.0
MarkupSafe==2.1.5
meson==0.63.0
more-itertools==10.2.0
mpmath==1.3.0
networkx==2.8.8
num2words==0.5.13
numba==0.59.1
numpy==1.26.4
openai-whisper==20231117
pycodestyle==2.8.0
python-crfsuite==0.9.10
python-dateutil==2.9.0.post0
pytz==2024.1
regex==2023.12.25
requests==2.27.1
scipy==1.13.0
six==1.16.0
sympy==1.12
tiktoken==0.6.0
toml==0.10.2
torch==2.2.2
tqdm==4.66.2
typing_extensions==4.11.0
tzdata==2024.1
tzlocal==5.2
urllib3==1.26.8
whisper-timestamped==1.15.3
zstandard==0.16.0
```

**Comment by sebastianrueckerai** [comment]
I installed importlib like this:
`C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\bin> .\python.exe -m pip install importlib`

And tried the included headless example - with the same error message about importlib.

I will try to replicate this on my main machine. This was under Wndows, will try on Linux next.

**Comment by sebastianrueckerai** [comment]
I think this may be the cause of the bug:
https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641/20

Are you perhaps not working with the latest Blender version and hence not with Python 3.11?
I am trying to find how "find_spec" is supposed to be used now, but the docs seem out of date.

**Comment by blackears** [comment]
I've made your change and it's running on my machine.  I'm using Blender 4.1 with python 3.11.7 and the old code works for me.  I'm running on Windows, though, so it might be working differently for me.

I've updated the 1.0.1 release.  Let me know if this resolves your issue.

**Comment by sebastianrueckerai** [comment]
The included example works now, many thanks for the quick help! :)
