### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by OmriSoudry** [blackears/parrotLipsync#4]
When I click the RENDER LIPSYNC TO ACTION / OBJECT NLA, I'm getting this error:

Adding phoneme  {'code': 'p', 'class': 'Stops', 'example': '*p*each, a*pp*le, ca*p*', 'group': 'M'}
Adding phoneme  {'code': 'b', 'class': 'Stops', 'example': '*b*ill, a*b*ove, ri*b*', 'group': 'M'}
Adding phoneme  {'code': 't', 'class': 'Stops', 'example': '*t*all, in*t*ernal, ligh*t*', 'group': 'C'}
Adding phoneme  {'code': 'd', 'class': 'Stops', 'example': '*d*ill, a*d*ore, ki*d*', 'group': 'C'}
Adding phoneme  {'code': 'k', 'class': 'Stops', 'example': '*c*ave, ti*ck*et, luc*k*', 'group': 'C'}
Adding phoneme  {'code': 'ɡ', 'class': 'Stops', 'example': '*g*ive, ba*gg*age, di*g*', 'group': 'C'}
Adding phoneme  {'code': 'f', 'class': 'Fricatives', 'example': '*ph*one, ra*ff*le, lea*f*', 'group': 'F'}
Adding phoneme  {'code': 'v', 'class': 'Fricatives', 'example': '*v*ideo, li*v*ely, lo*v*e', 'group': 'F'}
Adding phoneme  {'code': 'θ', 'class': 'Fricatives', 'example': '*th*in, au*th*or, ba*th*', 'group': 'TH'}
Adding phoneme  {'code': 'ð', 'class': 'Fricatives', 'example': '*th*ere, lea*th*er, brea*th*e', 'group': 'TH'}
Adding phoneme  {'code': 's', 'class': 'Fricatives', 'example': '*c*elery, pa*ss*ing, bu*s*', 'group': 'C'}
Adding phoneme  {'code': 'z', 'class': 'Fricatives', 'example': '*z*ebra, depo*s*it, shoe*s*', 'group': 'C'}
Adding phoneme  {'code': 'ʃ', 'class': 'Fricatives', 'example': '*sh*ell, o*c*ean, ru*sh*', 'group': 'SH'}
Adding phoneme  {'code': 'ʒ', 'class': 'Fricatives', 'example': '*g*enre, mea*s*ure, rou*ge*', 'group': 'SH'}
Adding phoneme  {'code': 'h', 'class': 'Fricatives', 'example': '*h*ill, a*h*ead', 'group': 'W'}
Adding phoneme  {'code': 'tʃ', 'class': 'Affricates', 'example': '*ch*ip, a*ch*ieve, dit*ch*', 'group': 'SH'}
Adding phoneme  {'code': 'dʒ', 'class': 'Affricates', 'example': '*j*ump, a*dj*oin, bri*dge*', 'group': 'SH'}
Adding phoneme  {'code': 'm', 'class': 'Nasals', 'example': '*m*ill, ha*mm*er, broo*m*', 'group': 'M'}
Adding phoneme  {'code': 'n', 'class': 'Nasals', 'example': '*n*ickel, su*nn*y, spoo*n*', 'group': 'N'}
Adding phoneme  {'code': 'ŋ', 'class': 'Nasals', 'example': 'si*ng*er, wro*ng*', 'group': 'N'}
Adding phoneme  {'code': 'l', 'class': 'Approximants', 'example': '*l*amb, si*ll*y, fa*ll*', 'group': 'L'}
Adding phoneme  {'code': 'ɹ', 'class': 'Approximants', 'example': '*r*obot, fu*rr*y, sta*r*', 'group': 'C'}
Adding phoneme  {'code': 'j', 'class': 'Approximants', 'example': '*y*ellow, ro*y*al', 'group': 'U'}
Adding phoneme  {'code': 'w', 'class': 'Approximants', 'example': '*w*inter, flo*w*er', 'group': 'W'}
Adding phoneme  {'code': 'ɾ', 'class': 'Flap', 'example': 'bu*tt*er, pe*d*al (only between vowels when the second syllable is unstressed)', 'group': 'rest'}
Adding phoneme  {'code': 'i', 'class': 'Front Vowels', 'example': 's*ee*, n*ea*t, p*ie*ce', 'group': 'A'}
Adding phoneme  {'code': 'ɪ', 'class': 'Front Vowels', 'example': 'p*i*n, b*i*t, l*i*ck', 'group': 'A'}
Adding phoneme  {'code': 'e', 'class': 'Front Vowels', 'example': 's*ay*, pl*a*ce, r*ai*n', 'group': 'A'}
Adding phoneme  {'code': 'ɛ', 'class': 'Front Vowels', 'example': 't*e*n, s*ai*d, br*ea*d', 'group': 'A'}
Adding phoneme  {'code': 'æ', 'class': 'Front Vowels', 'example': 'm*a*d, c*a*t, f*a*n', 'group': 'A'}
Adding phoneme  {'code': 'a', 'class': 'Front Vowels', 'example': 'f*a*r, st*a*rt', 'group': 'A'}
Adding phoneme  {'code': 'u', 'class': 'Back Vowels', 'example': 'p*oo*l, bl*ue*', 'group': 'O'}
Adding phoneme  {'code': 'ʊ', 'class': 'Back Vowels', 'example': 'l*oo*k, g*oo*d, b*u*sh', 'group': 'O'}
Adding phoneme  {'code': 'o', 'class': 'Back Vowels', 'example': 'thr*ow*, h*o*le, t*oe*', 'group': 'O'}
Adding phoneme  {'code': 'ʌ', 'class': 'Back Vowels', 'example': 'b*u*s, m*u*d, l*u*nch', 'group': 'U'}
Adding phoneme  {'code': 'ɔ', 'class': 'Back Vowels', 'example': 'st*o*re, m*o*re, c*o*rn', 'group': 'O'}
Adding phoneme  {'code': 'ɑ', 'class': 'Back Vowels', 'example': 'd*o*g, b*a*ll, f*a*ther', 'group': 'O'}
Adding phoneme  {'code': 'ə', 'class': 'Central Vowels', 'example': 'b*e*lieve, cinn*a*mon, s*u*rround (in an unstressed syllable)', 'group': 'EE'}
Adding phoneme  {'code': 'ɨ', 'class': 'Central Vowels', 'example': 'ros*e*s, want*e*d (in an unstressed syllable that is a suffix)', 'group': 'A'}
Adding phoneme  {'code': 'ɚ', 'class': 'Central Vowels', 'example': 'weath*er*, edit*or* (in an unstressed syllable with an r-quality)', 'group': 'A'}
Adding phoneme  {'code': 'ɝ', 'class': 'Central Vowels', 'example': 'b*ir*d, f*ur* (in a stressed syllable with an r-quality)', 'group': 'A'}
Adding phoneme  {'code': 'aɪ', 'class': 'Diphthongs', 'example': 'fl*y*, l*ie*, sm*i*le', 'group': 'A'}
Adding phoneme  {'code': 'eɪ', 'class': 'Diphthongs', 'example': 'dom*ai*n', 'group': 'A'}
Adding phoneme  {'code': 'aʊ', 'class': 'Diphthongs', 'example': 'n*ow*, fr*ow*n, l*ou*d', 'group': 'O'}
Adding phoneme  {'code': 'oʊ', 'class': 'Diphthongs', 'example': 'l*oa*d, bl*ow*ing', 'group': 'O'}
Adding phoneme  {'code': 'ɔɪ', 'class': 'Diphthongs', 'example': 'b*oy*, sp*oi*l, n*oi*se', 'group': 'O'}
Adding phoneme  {'code': 'ju', 'class': 'Diphthongs', 'example': 'c*ue*, f*ew*', 'group': 'U'}
Missing phoneme: "|"
Missing phoneme: "‖"
Missing phoneme: "d͡ʒ"
Missing phoneme: "‖"
Missing phoneme: "‖"
Missing phoneme: "t͡ʃ"
Missing phoneme: "t͡ʃ"
Missing phoneme: "‖"
Missing phoneme: "t͡ʃ"
Missing phoneme: "‖"
Missing phoneme: "‖"
Missing phoneme: "‖"
Missing phoneme: "d͡ʒ"
Missing phoneme: "‖"
Traceback (most recent call last):
  File "C:\Users\My User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\parrotLipsync\parrot_lipsync.py", line 931, in execute
    render_lipsync_to_action(context, tgt_action, seq)
  File "C:\Users\My User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\parrotLipsync\parrot_lipsync.py", line 699, in render_lipsync_to_action
    src_curve_y = fcurve_group[1][1]
IndexError: list index out of range
Error: Python: Traceback (most recent call last):
  File "C:\Users\My User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\parrotLipsync\parrot_lipsync.py", line 931, in execute
    render_lipsync_to_action(context, tgt_action, seq)
  File "C:\Users\My User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\parrotLipsync\parrot_lipsync.py", line 699, in render_lipsync_to_action
    src_curve_y = fcurve_group[1][1]
IndexError: list index out of range

I'm using the DEFAULT phoneme table, and defined all pose actions:
![image](https://github.com/blackears/parrotLipsync/assets/7345302/014b018d-6f1b-4d93-80c9-7e5f39be4726)

**Comment by blackears** [comment]
I'm not sure.  Would you be able to post a blender file demonstrating the error?

**Comment by blackears** [comment]
Another user had a similar error.  It seems to be related to compound attributes only having some of their fcurves set.  Could you  please try the attached archive and let me know if this solves the error?

[parrotLipsync.zip](https://github.com/blackears/parrotLipsync/files/15066217/parrotLipsync.zip)

**Comment by OmriSoudry** [comment]
Thanks, that solved it!
Now I only need to understand how to make the syllables more accurate and slower to look natural, but that's for another topic ;) 
Thank you for the quick help.

**Comment by blackears** [comment]
You're welcome.  I'm planning to put out 1.0.3 soon which will have this fix and others.  Part of making the animation look more natural is making better mouth poses, but you can also try adjusting the Strength parameter to just tone everything down a bit.  

I'm not sure what else can be done, aside from maybe finding a clever way to throw out unnecessary mouth keyframes. I think the flappiness of animations is coming from keyframing every phoneme.  Traditional animations tend to skip a lot of phonemes.
