### ISSUE TITLE
issue with ffmpeg not found in blender 4.1.1

### ISSUE THREAD

**Issue by schabert68** [blackears/parrotLipsync#7]
i need some help. I installed parrot addon, following the tutorial in your previous video (e.g installing ffmpeg) I am on mac ventura and blender 4.1.1. When I click on the "render lipsync to action, I get the following message:

 Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/site-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 1026, in _init_
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
 I do have ffmpeg 7.0.1 installed on my computer ( ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)).I have installed also whisper and gruut in blender. Can you please help as I am pulling my hair on this.

**Comment by blackears** [comment]
I don't have much experience with Apple.  Is ffmpeg on your path?

**Comment by schabert68** [comment]
hello,

That is at the thing. I assumed that I had to put ffmpeg on my path. but where ? where do I set the path?

Thank you.

M 07939597293
E ***@***.***
Serge Chabert Photography
1 Orangefield Place
Greenock PA15 1YX

www.sergechabert.photography
https://www.facebook.com/sergechabert6/
https://www.behance.net/photograph999b
https://sergechabert.wordpress.com
https://www.linkedin.com/in/serge-chabert-1b16073/

**Comment by blackears** [comment]
It looks like  you need to edit the /etc/paths file.  This web page explains how.

https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/#.Uydjga1dXDg

**Comment by blackears** [comment]
This webpage also describes installing ffmpeg on mac:

https://superuser.com/questions/624561/install-ffmpeg-on-os-x

**Comment by blackears** [comment]
Looking at the whisper source, it looks like it's trying to just run the ffmpeg command.  If it's failing, it means ffmpeg is either not installed or not added to your path.  If you can run `ffmpeg` from the command line, then the addon should work.

**Comment by schabert68** [comment]
hello,

ffmpeg is definitely installed :

￼
and the path has been added to the etc path file :

/usr/local/Cellar/ffmpeg/7.0.1/bin
/usr/local/bin
/System/Cryptexes/App/usr/bin
/usr/bin
/bin
/usr/sbin
/sbin

but I get the same issue:

￼

M 07939597293
E ***@***.***
Serge Chabert Photography
1 Orangefield Place
Greenock PA15 1YX

www.sergechabert.photography
https://www.facebook.com/sergechabert6/
https://www.behance.net/photograph999b
https://sergechabert.wordpress.com
https://www.linkedin.com/in/serge-chabert-1b16073/

**Comment by schabert68** [comment]
<img width="566" alt="Screenshot 2024-06-03 at 16 28 31" src="https://github.com/blackears/parrotLipsync/assets/71722145/5f050b2d-f567-482c-b14b-9ba794a1f7e0">
<img width="1584" alt="Screenshot 2024-06-03 at 16 34 40" src="https://github.com/blackears/parrotLipsync/assets/71722145/31100885-6461-47b8-b85e-0143a8db9c68">

**Comment by blackears** [comment]
Maybe restart your computer?  Are you able to run ffmpeg from the terminal?

**Comment by schabert68** [comment]
I have restarted my computer and I ran FFmpeg on terminal and it works.

However, in blender i get the same error.

M 07939597293
E ***@***.***
Serge Chabert Photography
1 Orangefield Place
Greenock PA15 1YX

www.sergechabert.photography
https://www.facebook.com/sergechabert6/
https://www.behance.net/photograph999b
https://sergechabert.wordpress.com
https://www.linkedin.com/in/serge-chabert-1b16073/

**Comment by blackears** [comment]
I'm not sure why that is happening.  This seems like an issue with Whisper and not something I can help with.

**Comment by schabert68** [comment]
I restarted my computer, I ran ffmpeg on terminal. it works as seen below :

> ffmpeg -i /Users/serge/audio/audio_test.wav /Users/serge/test/audio_test.mp4
> ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
>   built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
>   libavutil      59.  8.100 / 59.  8.100
>   libavcodec     61.  3.100 / 61.  3.100
>   libavformat    61.  1.100 / 61.  1.100
>   libavdevice    61.  1.100 / 61.  1.100
>   libavfilter    10.  1.100 / 10.  1.100
>   libswscale      8.  1.100 /  8.  1.100
>   libswresample   5.  1.100 /  5.  1.100
>   libpostproc    58.  1.100 / 58.  1.100
> [aist#0:0/pcm_s16le @ 0x7fe347707a40] Guessed Channel Layout: stereo
> Input #0, wav, from '/Users/serge/audio/audio_test.wav':
>   Duration: 00:00:05.94, bitrate: 1414 kb/s
>   Chapters:
>     Chapter #0:0: start 0.000000, end 5.941315
>       Metadata:
>         title           : Tempo: 120.0
>   Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
> Stream mapping:
>   Stream #0:0 -> #0:0 (pcm_s16le (native) -> aac (native))
> Press [q] to stop, [?] for help
> Output #0, mp4, to '/Users/serge/test/audio_test.mp4':
>   Metadata:
>     encoder         : Lavf61.1.100
>   Chapters:
>     Chapter #0:0: start 0.000000, end 5.941315
>       Metadata:
>         title           : Tempo: 120.0
>   Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
>       Metadata:
>         encoder         : Lavc61.3.100 aac
> [out#0/mp4 @ 0x7fe347707bc0] video:0KiB audio:72KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 3.344947%
> size=      75KiB time=00:00:05.94 bitrate= 103.0kbits/s speed=29.9x    
> [aac @ 0x7fe34770a180] Qavg: 15092.410
> ***@***.*** ~ % 



But I get the same issue in blender with parrot add-on.

M 07939597293
E ***@***.***
Serge Chabert Photography
1 Orangefield Place
Greenock PA15 1YX

www.sergechabert.photography
https://www.facebook.com/sergechabert6/
https://www.behance.net/photograph999b
https://sergechabert.wordpress.com
https://www.linkedin.com/in/serge-chabert-1b16073/

**Comment by blackears** [comment]
It might be related to permissions.  Does the ffmpeg binary have read and execute permissions for all users?

**Comment by schabert68** [comment]
Hello,I ran blender both in normal user and admin user snd hitting the same issue. But I will check again.Serge ***@***.***@aim.comhttps://sergechabert.wordpress.com/https://www.behance.net/photograph999bhttps://www.linkedin.com/in/serge-chabert-1b16073/http://www.blurb.co.uk/b/7896481-wild-flowers07939597293Room 111 Orangefield placeGreenockInverclydePA15 1YXUnited KingdomOn 3 Jun 2024, at 17:15, blackears ***@***.***> wrote:﻿
It might be related to permissions.  Does the ffmpeg binary have read and execute permissions for all users?

**Comment by schabert68** [comment]
I have tried everything you told me. I even tried to uninstall and reinstall blender, I tried uninstall and reinstall the parrot addon I tried to uninstall whisper_timestamped and gruut. I have set the proper permission on the ffmpeg binary. NOTHING works.This is very disheartening. i get the same error message : 
Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/site-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
 Please someone help !!!!!

**Comment by blackears** [comment]
I'm not sure why this is happening.  That's everything I can think of.  The code it is failing on is listed below.  There must be something odd about your setup that is preventing it from running.  Do you have a second computer you can try this on?

```
    # This launches a subprocess to decode audio while down-mixing
    # and resampling as necessary.  Requires the ffmpeg CLI in PATH.
    # fmt: off
    cmd = [
        "ffmpeg",
        "-nostdin",
        "-threads", "0",
        "-i", file,
        "-f", "s16le",
        "-ac", "1",
        "-acodec", "pcm_s16le",
        "-ar", str(sr),
        "-"
    ]
    # fmt: on
    try:
        out = run(cmd, capture_output=True, check=True).stdout
    except CalledProcessError as e:
        raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
```

**Comment by blackears** [comment]
This might be a long shot, but if you can edit the line to be the following it might work.  But this is part of the Whisper module so I have no way to do this on my end.  You'd have to edit the script on your machine.

`out = run(cmd, capture_output=True, check=True, shell=True).stdout`

**Comment by schabert68** [comment]
Where do i enter the code?On 4 Jun 2024, at 01:19, blackears ***@***.***> wrote:﻿
This might be a long shot, but if you can edit the line to be the following it might work.  But this is part of the Whisper module so I have no way to do this on my end.  You'd have to edit the script on your machine.
out = run(cmd, capture_output=True, check=True, shell=True).stdout

**Comment by schabert68** [comment]
after the change, i now get the following message:

Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/site-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True, shell=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', '/Users/serge/3d projects/father animations/original bought file/lip sync tutorial/old versions/audio/audio_test.wav', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 127.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/site-packages/whisper/audio.py", line 60, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: -nostdin: ffmpeg: command not found

**Comment by schabert68** [comment]
hello,
after the change, I now got this error message:

after the change, i now get the following message:

Python: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/site-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True, shell=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', '/Users/serge/3d projects/father animations/original bought file/lip sync tutorial/old versions/audio/audio_test.wav', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 127.


M 07939597293
E ***@***.***
Serge Chabert Photography
1 Orangefield Place
Greenock PA15 1YX

www.sergechabert.photography
https://www.facebook.com/sergechabert6/
https://www.behance.net/photograph999b
https://sergechabert.wordpress.com
https://www.linkedin.com/in/serge-chabert-1b16073/

**Comment by schabert68** [comment]
I justt give up. it still does not work.

**Comment by blackears** [comment]
Sorry, this is an issue with the underlying Whisper library which I have no control over.  I don't know why it isn't working.  I can only suggest trying this on a different machine.

**Comment by blackears** [comment]
I've posted a question about this in the Whisper discussion board.

https://github.com/openai/whisper/discussions/2199

**Comment by glangford** [comment]
Hello @schabert68 (visiting from the whisper discussion board)

I skimmed this thread and you have tried a lot of things already. Try copying the ffmpeg executable into /usr/local/bin?

**Comment by glangford** [comment]
...option 2: set the PYTHONPATH environment variable to the directory where you have ffmpeg installed

**Comment by schabert68** [comment]
I copied the executable into usr/local/bin.

Now I get this error message when I click on the "render lipsync to action" :

`bpy.ops.sequencer.sound_strip_add(filepath="//audio/hello_there.wav", directory="/Users/serge/3d-projects/father-animations/lip-sync-tutorial/old-versions/audio/", files=[{"name":"hello_there.wav", "name":"hello_there.wav"}], relative_path=True, frame_start=1, channel=1)
`

I tried another time and I gett this message:

`bpy.context.scene.props.lipsync_action = None
`

**Comment by schabert68** [comment]
I really don't understand, it is as if  it has a mind of it own !!!

**Comment by schabert68** [comment]
I reloaded my blender file and i am back to:

`bpy.ops.sequencer.sound_strip_add(filepath="//audio/hello_there.wav", directory="/Users/serge/3d-projects/father-animations/lip-sync-tutorial/old-versions/audio/", files=[{"name":"hello_there.wav", "name":"hello_there.wav"}], relative_path=True, frame_start=1, channel=1)
<img width="1700" alt="Screenshot 2024-06-05 at 23 03 09" 
`
<img width="1700" alt="Screenshot 2024-06-05 at 23 03 09" src="https://github.com/blackears/parrotLipsync/assets/71722145/923d569a-a843-43a4-9d0c-21693c5f830b">

<img width="1700" alt="Screenshot 2024-06-05 at 23 03 26" src="https://github.com/blackears/parrotLipsync/assets/71722145/57b2d166-9331-429e-a937-d793c1a798a9">

**Comment by glangford** [comment]
I don't know anything about blender but now that whisper isn't complaining, maybe someone else can take it from here 😊

**Comment by blackears** [comment]
Do you have the rest of the error message?

**Comment by schabert68** [comment]
i think I finally got the solution (Got it from chatgpt4).

I just need to go to blender console and enter the following code there and run it :
`import os
os.environ['PATH'] += os.pathsep + '/usr/local/bin'

from whisper.audio import load_audio  # Ensure this is after setting PATH

# Your existing code
`
Then when I run parrot buttton "render lipsync to action", it works.
<img width="1700" alt="Screenshot 2024-06-07 at 22 26 44" src="https://github.com/blackears/parrotLipsync/assets/71722145/fe72c9ba-7b69-4254-8e99-9c84d9759187">
