### ISSUE TITLE
Doesnt work in blender 4.1

### ISSUE THREAD

**Issue by Sim1603** [blackears/parrotLipsync#8]
Hello, tried render lypsunc to object in 4.1 and i get this error;

![image](https://github.com/blackears/parrotLipsync/assets/25005490/578b4209-9d3a-463a-b98c-fa5fdde8e562)

Works fine in 4.0

**Comment by blackears** [comment]
It looks like you did not install the whisper_timestamped library.  Please go through the setup and make sure all the required libraries are installed.

**Comment by Sim1603** [comment]
Ah, seems to work again, Id assumed the installed librries would work regardless blender version. Seems to work again! 

Thanks!
