### ISSUE TITLE
Error msg: "Whisper_Timestamped not installed" but it actually is installed...

### ISSUE THREAD

**Issue by golubsorin** [blackears/parrotLipsync#9]
Can I get some support with this? I tried a lot of options to install this whisper and I keep getting the same error in Blender 4.2.

![image](https://github.com/user-attachments/assets/b706d5ac-9784-45e5-b9f1-cbf76e6950b5)

**Comment by blackears** [comment]
Would you be able to open the System Console?  (Window > Toggle System Console).  Extra debugging info will be printed there.  Although I;m not sure there is much I can do about this particular error.

**Comment by blackears** [comment]
Parrot 1.1.0 should resolve this issue.  Please let me know if you're still having issues.

**Comment by blackears** [comment]
Closing in favor of https://github.com/blackears/parrotLipsync/issues/10
